functionality:
  name: guanlab_dengkw_je
  namespace: joint_embedding_methods

  # metadata for your method
  description: A description for your method.
  info:
    method_label: "Guanlab-dengkw"
    submission_id: "170795"
    team_name: Guanlab-dengkw
    # project_url: https://github.com/foo/bar
    # publication_doi: 10.1101/0123.45.67.890123
    # publication_url: https://arxiv.org/abs/1234.56789

  authors:
    - name: Kaiwen Deng
      email: dengkw@umich.edu
      roles: [ author, maintainer ]
      props: { github: nonztalk }

  # parameters
  arguments:
    # required inputs
    - name: "--input_mod1"
      type: "file"
      example: "dataset_mod1.h5ad"
      description: Modality 1 dataset.
      required: true
    - name: "--input_mod2"
      type: "file"
      example: "dataset_mod2.h5ad"
      description: Modality 2 dataset.
      required: true
    # required outputs
    - name: "--output"
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: Data for all cells in mod1 and mod2 embedded to ≤100 dimensions.
      required: true


  # files your script needs
  resources:
    - type: python_script
      path: script.py
  
# target platforms
platforms:
  - type: docker
    image: dataintuitive/randpy:py3.8
    setup:
      - type: python
        packages:
          - anndata
          - umap-learn
  - type: nextflow
    labels: [ vhighmem, hightime, vhighcpu ]
