functionality:
  name: guanlab_dengkw_pm
  namespace: predict_modality_methods
  
  # metadata for your method
  description: A description for your method.
  info:
    method_label: "Guanlab-dengkw"
    submission_id: "170636"
    team_name: Guanlab-dengkw
    # project_url: https://github.com/foo/bar
    # publication_doi: 10.1101/0123.45.67.890123
    # publication_url: https://arxiv.org/abs/1234.56789

  authors:
    - name: Kaiwen Deng
      email: dengkw@umich.edu
      roles: [ author, maintainer ]
      props: { github: nonztalk }
      
  # parameters
  arguments:
    # required inputs
    - name: "--input_train_mod1"
      type: "file"
      example: "dataset_mod1.h5ad"
      description: Censored dataset, training cells.
      required: true
    - name: "--input_test_mod1"
      type: "file"
      example: "dataset_mod1.h5ad"
      description: Censored dataset, test cells.
      required: true
    - name: "--input_train_mod2"
      type: "file"
      example: "dataset_mod2.h5ad"
      description: Censored dataset.
      required: true
    # required outputs
    - name: "--output"
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: Dataset with predicted values for modality2.
      required: true
    # additional parameters
    - name: "--distance_method"
      type: "string"
      default: "minkowski"
      description: The distance metric to use. Possible values include `euclidean` and `minkowski`.
    - name: "--n_pcs"
      type: "integer"
      default: 50
      description: Number of components to use for dimensionality reduction.
      
  # files your script needs
  resources:
    - type: python_script
      path: script.py
      
# target platforms
platforms:
  - type: docker
    image: dataintuitive/randpy:py3.8
    setup:

      - type: python
        packages:
          - scikit-learn
          - anndata
          - pandas
          - numpy
          - scanpy

  - type: nextflow
    labels: [ vhighmem, vvhightime, vhighcpu ]
